//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreatorFollower
    {
        public int followingUserId { get; set; }
        public int followedeUserID { get; set; }
    
        public virtual CreatorFollower CreatorFollowers1 { get; set; }
        public virtual CreatorFollower CreatorFollower1 { get; set; }
        public virtual CreatorUser CreatorUser { get; set; }
    }
}
